// Generated by CoffeeScript 1.6.2
(function() {
  var config, fs, helps, relativePath;

  fs = require('fs');

  config = require('../config');

  relativePath = 'db/migrate';

  (function() {
    var dir, targetPath, _i, _len, _ref, _results;

    targetPath = global.__basepath;
    _ref = relativePath.split('/');
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      dir = _ref[_i];
      targetPath += "/" + dir;
      _results.push((function() {
        var _results1;

        _results1 = [];
        while (!fs.existsSync(targetPath)) {
          _results1.push(fs.mkdirSync(targetPath));
        }
        return _results1;
      })());
    }
    return _results;
  })();

  helps = {
    create: function() {
      return console.log('example: cake -n [file_name] db:migrate:create');
    }
  };

  exports.help = function(task) {
    return helps[task]()(helps[task] != null ? void 0 : console.log('missing help'));
  };

  exports.migrate = function(options) {
    return console.log(config('dev'));
  };

  exports.create = function(options) {
    var fileName;

    if (options.name != null) {
      fileName = new Date().toJSON().replace(/[^0-9]/g, '') + ("_" + options.name + ".coffee");
      return fs.writeFile("" + relativePath + "/" + fileName, '', function(err) {
        return console.log("file " + fileName + " created");
      });
    } else {
      console.log('missing file name');
      return helps.create();
    }
  };

}).call(this);
