// Generated by CoffeeScript 1.6.2
(function() {
  var colors, fs, moment;

  colors = require('colors');

  fs = require('fs');

  moment = require('moment');

  exports.help = function() {
    console.log("example:");
    return console.log("  cake -n [file_name] db:migrate:create");
  };

  exports.main = function(options) {
    var fileName;

    if (options.name != null) {
      fileName = moment().format('YYYYMMDDHHmmss') + ("_" + options.name + ".coffee");
      return fs.writeFile("db/migrate/" + fileName, '', function(err) {
        return console.log(("file " + fileName + " created").green);
      });
    } else {
      console.log('missing file name'.red);
      return this.help();
    }
  };

}).call(this);
