// Generated by CoffeeScript 1.6.2
(function() {
  var async, colors, db, fs;

  fs = require('fs');

  async = require('async');

  colors = require('colors');

  db = require('../../../db');

  exports.main = function(options) {
    return console.log('not implement yet');
  };

}).call(this);
