// Generated by CoffeeScript 1.6.2
(function() {
  var fs, path;

  path = require('path');

  fs = require('fs');

  global.__basepath = fs.realpathSync('.');

  exports.tasks = function() {
    option('-h', '--help', 'show helps');
    option('-n', '--name [file]', 'set the migrate file name');
    task('db:migrate', 'migrate the database', function(options) {
      return require('./tasks/migrate').migrate(options);
    });
    task('db:migrate:create', 'create a migrate file', function(options) {
      return require('./tasks/migrate').create(options);
    });
    return task('db:migrate:status', 'display status of migrations', function(options) {
      return require('./tasks/migrate').status();
    });
  };

}).call(this);
