// Generated by CoffeeScript 1.6.2
(function() {
  var configs, mergeConfigs;

  configs = {
    db: require("" + global.__basepath + "/config/db")
  };

  mergeConfigs = {};

  (function() {
    var k, kk, _results;

    _results = [];
    for (k in configs) {
      _results.push((function() {
        var _results1;

        _results1 = [];
        for (kk in configs[k]) {
          _results1.push(mergeConfigs[kk] = configs[k][kk]);
        }
        return _results1;
      })());
    }
    return _results;
  })();

  module.exports = function(key, file) {
    if ((file != null) && (configs[file] != null)) {
      return configs[file][key];
    } else {
      return mergeConfigs[key];
    }
  };

}).call(this);
