// Generated by CoffeeScript 1.6.2
(function() {
  var Migrate, async, colors, db, fs,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  fs = require('fs');

  async = require('async');

  colors = require('colors');

  db = require('../../db');

  Migrate = require('../../modules/migrate');

  exports.main = function(options) {
    var tPath;

    console.log('migrate start');
    tPath = "" + global.__basepath + "/db/migrate";
    return fs.readdir(tPath, function(err, fileList) {
      if (err != null) {
        throw err.red;
      }
      fileList.sort();
      return db.loadSchema(function(err, schema) {
        return async.eachSeries(fileList, (function(file, next) {
          var mig, task, version;

          version = file.split('_')[0];
          if (__indexOf.call(schema, version) >= 0) {
            return next();
          } else {
            console.log(new Array(60).join('-'));
            console.log("migrate file " + file);
            task = require("" + tPath + "/" + file);
            mig = new Migrate(version, task);
            return mig.start(next);
          }
        }), function(err) {
          if (err != null) {
            console.log(err.toString().red);
          } else {
            console.log('migrate finish'.green);
          }
          return process.exit();
        });
      });
    });
  };

}).call(this);
