// Generated by CoffeeScript 1.6.2
(function() {
  var colors;

  colors = require('colors');

  exports.A = (function() {
    function _Class() {}

    _Class.prototype.a = function() {};

    return _Class;

  })();

  exports.help = function() {
    console.log("example:");
    console.log("  cake -v 1 db:rollback");
    return console.log("  cake -v 20130530093101810 db:rollback");
  };

  exports.main = function(options) {
    var version;

    version = options.version != null ? options.version : 1;
    if (!/\d+/.test(version)) {
      console.log('invalid version'.red);
      return this.help();
    } else if (/\d{17}/.test(version)) {
      return console.log("rollback to version " + version);
    } else {
      return console.log("rollback last " + version + " versions");
    }
  };

}).call(this);
